In [1]:
import numpy as np

## DataTypes & Attrubutes

In [2]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [15]:
a2 = np.array([[1, 2, 3.3],
              [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18]]])

In [16]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [17]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [18]:
a1.shape

(3,)

In [19]:
a2.shape

(2, 3)

In [20]:
a3.shape

(3, 2, 3)

In [21]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [23]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [24]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [25]:
# confirming a3 has 18 elements
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [27]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [28]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [29]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [31]:
sample_array.dtype

dtype('int32')

In [32]:
ones = np.ones((2, 3))

In [33]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [34]:
ones.dtype

dtype('float64')

In [35]:
type(ones)

numpy.ndarray

In [36]:
zeros = np.zeros((2,3))

In [37]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [38]:
# arange(start, stop, step)
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [39]:
# random(low, high, shape)
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[0, 6, 5, 2, 1],
       [1, 8, 4, 2, 1],
       [0, 9, 4, 7, 0]])

In [40]:
random_array.size

15

In [41]:
random_array.shape

(3, 5)

In [44]:
random_array2 = np.random.random((5, 3))
random_array2

array([[0.8402412 , 0.06682795, 0.44979995],
       [0.73181289, 0.1028755 , 0.33892444],
       [0.02029588, 0.75270465, 0.71085901],
       [0.44227553, 0.27424681, 0.6547865 ],
       [0.05010116, 0.76717092, 0.93969622]])

In [45]:
random_array2.shape

(5, 3)

In [47]:
random_array3 = np.random.rand(5, 3)
random_array3

array([[0.54879642, 0.2054225 , 0.99455054],
       [0.86450046, 0.96345779, 0.27301343],
       [0.79540349, 0.35815366, 0.0432664 ],
       [0.16274148, 0.52000779, 0.41764808],
       [0.4967694 , 0.7638555 , 0.94096586]])

In [48]:
# Pseudo-random numbers
np.random.seed()