In [1]:
import numpy as np

## 1. DataTypes & Attrubutes

In [2]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2, 3.3],
              [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(3, 2, 3)

In [10]:
# returns the number of dimensions in an array
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
# confirming a3 has 18 elements
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [14]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [15]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [16]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [17]:
sample_array.dtype

dtype('int32')

In [18]:
ones = np.ones((2, 3))

In [19]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
ones.dtype

dtype('float64')

In [21]:
type(ones)

numpy.ndarray

In [22]:
zeros = np.zeros((2,3))

In [23]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
# arange(start, stop, step)
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [25]:
# random(low, high, shape)
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[3, 6, 2, 0, 9],
       [6, 0, 0, 3, 0],
       [3, 6, 7, 0, 1]])

In [26]:
random_array.size

15

In [27]:
random_array.shape

(3, 5)

In [28]:
random_array2 = np.random.random((5, 3))
random_array2

array([[0.77124894, 0.98478434, 0.54517935],
       [0.36422211, 0.24496345, 0.38233918],
       [0.38077953, 0.9828976 , 0.57380584],
       [0.99126523, 0.43885446, 0.8682638 ],
       [0.43303464, 0.42737319, 0.62364788]])

In [29]:
random_array2.shape

(5, 3)

In [30]:
random_array3 = np.random.rand(5, 3)
random_array3

array([[0.97143249, 0.26725332, 0.75514517],
       [0.65892579, 0.81218286, 0.17819382],
       [0.76959608, 0.78594183, 0.23020739],
       [0.74255254, 0.39191567, 0.22580511],
       [0.16442676, 0.13344251, 0.70383739]])

In [39]:
# Pseudo-random numbers
np.random.seed(seed=99999)
# random set of numbers below will not change, however many times you run this cell
random_array4 = np.random.randint(10, size=(5, 3))
random_array4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [40]:
random_array4.shape

(5, 3)

In [44]:
np.random.seed(7)
random_array5 = np.random.random((5, 3))
random_array5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [48]:
# without the seed function, random array before will give us different nums
random_array5 = np.random.random((5, 3))
random_array5

array([[0.95546832, 0.68291385, 0.05312869],
       [0.30885268, 0.59259469, 0.23512041],
       [0.964971  , 0.94504822, 0.84840088],
       [0.472324  , 0.84147671, 0.13111064],
       [0.30873366, 0.46299639, 0.7418472 ]])

## 3. Viewing arrays and matrices

In [50]:
# find unique numbers in an array
np.unique(random_array4)

array([0, 1, 3, 4, 5, 6, 8, 9])

In [51]:
a1

array([1, 2, 3])

In [52]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [53]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [54]:
a1[0]

1

In [59]:
a2.shape

(2, 3)

In [60]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [55]:
a2[0]

array([1. , 2. , 3.3])

In [61]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [56]:
a3.shape

(3, 2, 3)

In [57]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [63]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [64]:
a2[1]

array([4. , 5. , 6.5])

In [65]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [67]:
a3.shape

(3, 2, 3)

In [66]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [69]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[0, 1, 0, 1, 8],
         [4, 1, 6, 8, 5],
         [2, 4, 7, 4, 1],
         [2, 8, 5, 2, 9]],

        [[6, 2, 5, 7, 7],
         [5, 5, 6, 0, 6],
         [4, 6, 2, 6, 8],
         [7, 0, 5, 8, 9]],

        [[7, 7, 6, 2, 5],
         [6, 1, 9, 3, 4],
         [0, 3, 5, 6, 4],
         [0, 4, 1, 5, 2]]],


       [[[4, 8, 7, 5, 7],
         [5, 3, 7, 6, 2],
         [3, 1, 1, 8, 4],
         [2, 1, 7, 0, 8]],

        [[8, 1, 2, 3, 0],
         [1, 1, 5, 5, 6],
         [0, 9, 3, 2, 4],
         [2, 8, 4, 9, 0]],

        [[0, 2, 6, 3, 9],
         [5, 4, 6, 9, 9],
         [9, 4, 8, 2, 4],
         [6, 5, 3, 5, 2]]]])

IMPORTANT!!! how to read shapes:

- last element in shape starts from innermost bracket
- each previous number goes to the next outer bracket

In [70]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [73]:
# Get the first 4 numbers of the innermost arrays
a4[:, :, :, :4]

array([[[[0, 1, 0, 1],
         [4, 1, 6, 8],
         [2, 4, 7, 4],
         [2, 8, 5, 2]],

        [[6, 2, 5, 7],
         [5, 5, 6, 0],
         [4, 6, 2, 6],
         [7, 0, 5, 8]],

        [[7, 7, 6, 2],
         [6, 1, 9, 3],
         [0, 3, 5, 6],
         [0, 4, 1, 5]]],


       [[[4, 8, 7, 5],
         [5, 3, 7, 6],
         [3, 1, 1, 8],
         [2, 1, 7, 0]],

        [[8, 1, 2, 3],
         [1, 1, 5, 5],
         [0, 9, 3, 2],
         [2, 8, 4, 9]],

        [[0, 2, 6, 3],
         [5, 4, 6, 9],
         [9, 4, 8, 2],
         [6, 5, 3, 5]]]])

## 4. Manipulating & comparing arrays

### Arithmetic

In [75]:
a1

array([1, 2, 3])

In [77]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [78]:
a1 + ones

array([2., 3., 4.])

In [79]:
a1 - ones

array([0., 1., 2.])

In [80]:
a1 * ones

array([1., 2., 3.])

In [83]:
a1

array([1, 2, 3])

In [81]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [82]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [84]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [87]:
a2 * a3

array([[[  1. ,   4. ,   9.9],
        [ 16. ,  25. ,  39. ]],

       [[  7. ,  16. ,  29.7],
        [ 40. ,  55. ,  78. ]],

       [[ 13. ,  28. ,  49.5],
        [ 64. ,  85. , 117. ]]])

#### NumPy broadcasting
- describes how numpy treats arrays with different shapes during arithmetic operations
- subject to certain constraints, the smaller array is 'broadcast' across the larger array so that they have compatible shapes
- the broadcasting rule relaxes this constraing when the arrays' shapes meet certain constraints
- mismatched shapes errors are common!
When operating on 2 arrays, shapes are compared element-wise. Numpy first starts with trailing dimensions, and then works its way forward. 2 dimensions are compatible when:
  1. they are equal, or
  2. one of them is 1

In [88]:
a1 / ones

array([1., 2., 3.])

In [90]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [89]:
# floor division removes the decimals and rounds down
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [92]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [91]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [93]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [94]:
# same as a1 + ones
np.add(a1, ones)

array([2., 3., 4.])

In [96]:
# modulo
a1 % 2

array([1, 0, 1], dtype=int32)

In [100]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [101]:
a2 % 2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [103]:
a1

array([1, 2, 3])

In [102]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [104]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation