# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np


In [6]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1, 2, 3])
print(a1.ndim)

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1, 2, 3],
              [4, 5, 6]])

print(a2.ndim)

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([
              [[1, 2, 3], [4, 5, 6]],
              [[7, 8, 9], [10, 11, 12]],
              [[13, 14, 15], [16, 17, 18]]  
              ])

print(a3.ndim)

1
2
3


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [7]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)


((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [8]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [9]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((3, 2, 3), 3, dtype('int32'), 18, numpy.ndarray)

In [13]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
d1 = pd.DataFrame(a1)
d1


0
0  1
1  2
2  3

In [14]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10, 2))
ones


array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [16]:
# Create an array within a range of 0 and 100 with step 3
range = np.arange(0, 100, 3)
range


array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [17]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_numbers = np.random.randint(0, 10, size=(7,2))
random_numbers

array([[8, 9],
       [0, 4],
       [0, 6],
       [3, 9],
       [4, 1],
       [5, 4],
       [5, 3]])

In [19]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_floats = np.random.random((3, 5))
random_floats


array([[0.97169234, 0.94421451, 0.50622513, 0.37981762, 0.89995609],
       [0.5085473 , 0.68352414, 0.8840014 , 0.35033761, 0.76761846],
       [0.90427771, 0.0859325 , 0.58254064, 0.86650456, 0.48455891]])

In [25]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array2 = np.random.randint(10, size=(4, 6))
random_array2

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [27]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array3 = np.random.randint(1, 10, size=(3, 7))
print(random_array3)

# Find the unique numbers in the array you just created
np.unique(random_array3)

[[7 8 3 1 4 2 8]
 [4 2 6 6 4 6 2]
 [2 4 8 7 9 8 5]]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
# Find the 0'th index of the latest array you created
random_array3[0]


array([7, 8, 3, 1, 4, 2, 8])

In [31]:
# Get the first 2 rows of latest array you created
random_array3[:2, :]


array([[7, 8, 3, 1, 4, 2, 8],
       [4, 2, 6, 6, 4, 6, 2]])

In [32]:
# Get the first 2 values of the first 2 rows of the latest array
random_array3[:2, :2]

array([[7, 8],
       [4, 2]])

In [57]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array4 = np.random.randint(10, size=(3, 5))
ones_1 = np.ones((3, 5))

random_array4, ones_1

(array([[6, 6, 7, 4, 2],
        [7, 5, 2, 0, 2],
        [4, 2, 0, 4, 9]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [58]:
# Add the two arrays together
add = ones_1 + random_array4

In [59]:
# Create another array of ones of shape (5, 3)
ones_2 = np.ones((5,3))

In [60]:
# Try add the array of ones and the other most recent array together
# ones_2 + ones_1

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [61]:
# Create another array of ones of shape (3, 5)
ones_3 = np.ones((3, 5))
ones_3


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [62]:
# Subtract the new array of ones from the other most recent array
subtract = ones_3 - ones_2.T

In [63]:
# Multiply the ones array with the latest array
multiply = ones_3 * ones_2.T

In [64]:
# Take the latest array to the power of 2 using '**'
add ** 2

array([[ 49.,  49.,  64.,  25.,   9.],
       [ 64.,  36.,   9.,   1.,   9.],
       [ 25.,   9.,   1.,  25., 100.]])

In [67]:
# Do the same thing with np.square()
square = np.square(add)

In [68]:
# Find the mean of the latest array using np.mean()
np.mean(square)

31.666666666666668

In [69]:
# Find the maximum of the latest array using np.max()
np.max(square)

100.0

In [70]:
# Find the minimum of the latest array using np.min()
np.min(square)

1.0

In [71]:
# Find the standard deviation of the latest array
np.std(square)

27.62768337897495

In [76]:
# Find the variance of the latest array
print(np.var(square))
np.std(square) ** 2


763.2888888888888


763.2888888888888

In [80]:
# Reshape the latest array to (3, 5, 1)
print(square)
reshaped_square = square.reshape((3, 5, 1))
reshaped_square

[[ 49.  49.  64.  25.   9.]
 [ 64.  36.   9.   1.   9.]
 [ 25.   9.   1.  25. 100.]]


array([[[ 49.],
        [ 49.],
        [ 64.],
        [ 25.],
        [  9.]],

       [[ 64.],
        [ 36.],
        [  9.],
        [  1.],
        [  9.]],

       [[ 25.],
        [  9.],
        [  1.],
        [ 25.],
        [100.]]])

In [81]:
# Transpose the latest array
reshaped_square.T

array([[[ 49.,  64.,  25.],
        [ 49.,  36.,   9.],
        [ 64.,   9.,   1.],
        [ 25.,   1.,  25.],
        [  9.,   9., 100.]]])

What does the transpose do?

In [89]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
random_integers_1 = np.random.randint(10, size=(3, 3))
random_integers_2 = np.random.randint(10, size=(3, 2))
random_integers_1, random_integers_2


(array([[2, 6, 5],
        [7, 8, 4],
        [0, 2, 9]]),
 array([[7, 5],
        [7, 8],
        [3, 0]]))

In [90]:
# Perform a dot product on the two newest arrays you created
np.dot(random_integers_1, random_integers_2)

array([[ 71,  58],
       [117,  99],
       [ 41,  16]])

In [92]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
random_integers_3 = np.random.randint(10, size=(4, 3))
random_integers_4 = np.random.randint(10, size=(4, 3))
random_integers_3, random_integers_4


(array([[6, 3, 6],
        [7, 0, 5],
        [7, 4, 3],
        [1, 5, 5]]),
 array([[0, 8, 5],
        [2, 3, 3],
        [2, 9, 2],
        [2, 3, 6]]))

In [94]:
# Perform a dot product on the two newest arrays you created
# np.dot(random_integers_3, random_integers_4)

It doesn't work. How would you fix it?

In [95]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(random_integers_3, random_integers_4.T)

array([[54, 39, 51, 57],
       [25, 29, 24, 44],
       [47, 35, 56, 44],
       [65, 32, 57, 47]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [104]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
rand1 = np.random.randint(10, size=(4, 3))
rand2 = np.random.randint(10, size=(4, 3))
rand1, rand2


(array([[2, 3, 7],
        [5, 7, 0],
        [7, 3, 0],
        [7, 3, 5]]),
 array([[7, 3, 2],
        [8, 2, 8],
        [1, 1, 1],
        [5, 2, 8]]))

In [105]:
# Compare the two arrays with '>'
rand1 > rand2

array([[False, False,  True],
       [False,  True, False],
       [ True,  True, False],
       [ True,  True, False]])

What happens when you compare the arrays with `>`?

In [106]:
# Compare the two arrays with '>='
rand1 >= rand2

array([[False,  True,  True],
       [False,  True, False],
       [ True,  True, False],
       [ True,  True, False]])

In [107]:
# Find which elements of the first array are greater than 7
rand1 > 7

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [108]:
# Which parts of each array are equal? (try using '==')
rand1 == rand2

array([[False,  True, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [109]:
# Sort one of the arrays you just created in ascending order
rand1, np.sort(rand1)

(array([[2, 3, 7],
        [5, 7, 0],
        [7, 3, 0],
        [7, 3, 5]]),
 array([[2, 3, 7],
        [0, 5, 7],
        [0, 3, 7],
        [3, 5, 7]]))

In [110]:
# Sort the indexes of one of the arrays you just created
np.argsort(rand1)

array([[0, 1, 2],
       [2, 0, 1],
       [2, 1, 0],
       [1, 2, 0]], dtype=int64)

In [113]:
# Find the index with the maximum value in one of the arrays you've created
rand1, np.argmax(rand1)


(array([[2, 3, 7],
        [5, 7, 0],
        [7, 3, 0],
        [7, 3, 5]]),
 2)

In [114]:
# Find the index with the minimum value in one of the arrays you've created
rand1, np.argmin(rand1)

(array([[2, 3, 7],
        [5, 7, 0],
        [7, 3, 0],
        [7, 3, 5]]),
 5)

In [117]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
rand1, np.argmax(rand1, axis=1)


(array([[2, 3, 7],
        [5, 7, 0],
        [7, 3, 0],
        [7, 3, 5]]),
 array([2, 1, 0, 0], dtype=int64))

In [118]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
rand1, np.argmin(rand1, axis=0)

(array([[2, 3, 7],
        [5, 7, 0],
        [7, 3, 0],
        [7, 3, 5]]),
 array([0, 0, 1], dtype=int64))

In [138]:
# Create an array of normally distributed random numbers
np.random.normal(10, 2, size=(2, 3))
np.random.randn(5, 3)

array([[ 0.26931765,  1.81366658,  0.4045829 ],
       [ 0.09007259,  0.08273044, -0.25841774],
       [ 1.18348232, -0.50544227, -1.35678548],
       [-1.58165393,  0.07900901,  1.06069246],
       [ 0.23748525, -0.31736879,  0.4584413 ]])

In [146]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.